### ISSUE TITLE
when the plugin is enabled that scrolling the 'scene properties' tab is slow and laggy. 

### ISSUE THREAD

**Issue by theoryshaw** [brunopostle/ifc-git#1]
I noticed when the plugin is enabled that scrolling the 'scene properties' tab is slow and laggy. 

![2023-03-19_13-35-55_Blender_blender](https://user-images.githubusercontent.com/507113/226199247-53759848-dc54-4b2c-b8f3-3ad3e4f3b2d7.gif)

**Comment by brunopostle** [comment]
Yes it's doing lots of checks in each refresh, in particular it is searching for the repository each time, which looks like it is slow on your system. The latest code actually searches recursively if it can't find a repository, which will be even slower.

I'll find some way of caching this result.

If you 'minimise' the IFC git panel, is it normal speed?

BTW you have made your Desktop into a repository, which probably isn't that bad, but not very advisable.

**Comment by lfertig** [comment]
+1, and yes, minimising the panel helps resolve the lag

**Comment by brunopostle** [comment]
Closing, as e133a94 is now much faster. There are further potential optimisations, so feel free to reopen this issue if there is still a problem.
