### ISSUE TITLE
Working in a repo from another owner

### ISSUE THREAD

**Issue by brunoperdigao** [brunopostle/ifc-git#10]
When I add a file that comes from a repo from another owner, the ifc-git panel doesn't show any options.
I figure that this is a git standard behavior and I had to add the path as a safe directory using `git config --global --add safe.directory `%PATH%'. This solved the problem.
I don't know if it is possible, but maybe, in cases like this, there could be a button in the UI that would trigger this configuration.

**Comment by brunopostle** [comment]
I'm learning a lot about Git, I didn't know about this feature. I think that the add-on should show an error message if the repository exists, but isn't accessible like this.

Actually sharing a repository between multiple users is probably quite dangerous, but I can see that it may not be possible to control ownership on network drives etc..

**Comment by brunopostle** [comment]
Closing old bugs as I'm archiving this repository
